import { describe, expect, test } from "vitest";
import {
  SEED_ADMIN_ID,
  SEED_ORG_ID,
  SEED_PERFORMANCE_ORG_ID,
  SEED_STUDENT_1_ID,
} from "../src/drizzle/seed/constants";
import { idSchema } from "../src/lib/id-schema";

describe("idSchema", () => {
  // The regression this schema exists for: `z.uuid()` enforces the RFC 9562
  // version/variant nibbles, which these hand-written ids don't carry, so it
  // rejected the app's own rows. The Google Forms connect handshake validated
  // its state cookie that way and failed with `invalid_state` for every
  // seeded organization.
  test.each([
    ["seeded org", SEED_ORG_ID],
    ["seeded performance org", SEED_PERFORMANCE_ORG_ID],
    ["seeded admin", SEED_ADMIN_ID],
    ["seeded student", SEED_STUDENT_1_ID],
  ])("accepts the %s id", (_label, id) => {
    expect(idSchema.safeParse(id).success).toBe(true);
  });

  test.each([
    ["a v4 uuid", "3f2504e0-4f89-41d3-9a0c-0305e82c3301"],
    ["a v7 uuid", "0197f3c5-8f6a-7b21-9c3d-4e5f60718293"],
  ])("accepts %s, as generated by defaultRandom()", (_label, id) => {
    expect(idSchema.safeParse(id).success).toBe(true);
  });

  test.each([
    ["an empty string", ""],
    ["free text", "not-a-uuid"],
    ["a uuid missing a group", "00000000-0000-0000-000000000000"],
    ["a uuid with a non-hex character", "0000000g-0000-0000-0000-0000000000a1"],
    ["a uuid with trailing text", "00000000-0000-0000-0000-0000000000a1x"],
    ["SQL-ish input", "' OR 1=1 --"],
  ])("rejects %s", (_label, value) => {
    expect(idSchema.safeParse(value).success).toBe(false);
  });
});
