import { relations } from "drizzle-orm";
import {
  foreignKey,
  index,
  integer,
  pgEnum,
  pgTable,
  timestamp,
  unique,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { OrganizationsTable, UsersTable } from "@/drizzle/schemas/auth";
import { LecturesTable } from "@/drizzle/schemas/content";
import { createdAt, id, updatedAt } from "@/drizzle/schemas/helpers";
import { ZoomClientsTable } from "@/drizzle/schemas/live";
import { GroupsTable } from "./groups-table";

export const sessionStatusValues = [
  "scheduled",
  "ongoing",
  "completed",
  "cancelled",
] as const;
export type SessionStatus = (typeof sessionStatusValues)[number];
export const sessionStatusEnum = pgEnum("session_status", sessionStatusValues);

// One occurrence of a group's weekly schedule, generated by the
// `group/schedule-changed` Inngest function. Named `sessions`, not SOURCE's
// `zoom_sessions` (STATE.md D80): a class session is the domain concept and
// exists whether or not the org ever connects Zoom — the Zoom columns below
// stay null for an org that never connects one.
export const SessionsTable = pgTable(
  "sessions",
  {
    id,
    organizationId: uuid()
      .notNull()
      .references(() => OrganizationsTable.id, { onDelete: "cascade" }),
    groupId: uuid().notNull(),
    scheduledAt: timestamp({ withTimezone: true }).notNull(),
    durationMinutes: integer().notNull(),
    status: sessionStatusEnum().notNull().default("scheduled"),
    // Both are plain single-column FKs rather than the composite
    // (organizationId, x) shape used elsewhere: Postgres nulls *every* column
    // named in a composite FK's SET NULL action, including the NOT NULL
    // organizationId, so the delete throws instead of clearing the pointer
    // (STATE.md D79). Callers must therefore verify these belong to
    // ctx.organizationId before writing.
    teacherId: uuid().references(() => UsersTable.id, { onDelete: "set null" }),
    lectureId: uuid().references(() => LecturesTable.id, {
      onDelete: "set null",
    }),
    // Which connected Zoom account hosts this session's meeting, and the
    // meeting it created. All null for an "offline" session — an org that
    // never connects Zoom still schedules classes (phase-06.md step 3), so
    // every read path treats these as optional rather than expected.
    zoomClientId: uuid(),
    // Zoom's meeting id is a number, but it is an identifier and not an
    // amount: stored as text so it is never rounded or arithmetic'd.
    zoomMeetingId: varchar({ length: 64 }),
    zoomMeetingPassword: varchar({ length: 64 }),
    zoomJoinUrl: varchar({ length: 1024 }),
    // Host link. Grants host rights to whoever opens it, so it is only ever
    // selected for the assigned teacher or an org admin (sessions/lib
    // resolve-session-links.ts).
    zoomStartUrl: varchar({ length: 2048 }),
    // Filled by the `recording.completed` webhook, and only for accounts whose
    // plan records to the cloud — nothing forces recording on (STATE.md D101),
    // so a null here means "no recording", never "not loaded yet".
    zoomRecordingUrl: varchar({ length: 2048 }),
    zoomRecordingPassword: varchar({ length: 64 }),
    createdAt,
    updatedAt,
  },
  (table) => [
    index("sessions_organization_id_idx").on(table.organizationId),
    index("sessions_group_id_idx").on(table.groupId),
    index("sessions_scheduled_at_idx").on(table.scheduledAt),
    index("sessions_status_idx").on(table.status),
    // Makes regeneration idempotent — re-running the generator for an
    // unchanged schedule can be an onConflictDoNothing insert instead of a
    // delete-and-recreate that would churn ids on every save.
    unique("sessions_group_id_scheduled_at_unique").on(
      table.groupId,
      table.scheduledAt,
    ),
    // Phase 6's session_students hangs a composite FK off this pair.
    unique("sessions_organization_id_id_unique").on(
      table.organizationId,
      table.id,
    ),
    foreignKey({
      name: "sessions_organization_group_fk",
      columns: [table.organizationId, table.groupId],
      foreignColumns: [GroupsTable.organizationId, GroupsTable.id],
    }).onDelete("cascade"),
    // Composite, so a session can never point at another org's Zoom account.
    // Deliberately NO ACTION rather than SET NULL (which would try to null the
    // NOT NULL organizationId too, STATE.md D79) and rather than CASCADE
    // (losing the Zoom account must not delete the classes it hosted).
    // Disconnecting is a soft delete, so the row a session points at stays
    // readable; deleting the organization cascades both tables in one
    // statement, which NO ACTION tolerates.
    foreignKey({
      name: "sessions_organization_zoom_client_fk",
      columns: [table.organizationId, table.zoomClientId],
      foreignColumns: [ZoomClientsTable.organizationId, ZoomClientsTable.id],
    }),
    // The meeting-sync function asks "which sessions is this Zoom account
    // already hosting in this window?" on every provisioning run.
    index("sessions_zoom_client_id_idx").on(table.zoomClientId),
  ],
);

export const sessionsRelations = relations(SessionsTable, ({ one }) => ({
  organization: one(OrganizationsTable, {
    fields: [SessionsTable.organizationId],
    references: [OrganizationsTable.id],
  }),
  group: one(GroupsTable, {
    fields: [SessionsTable.groupId],
    references: [GroupsTable.id],
  }),
  teacher: one(UsersTable, {
    fields: [SessionsTable.teacherId],
    references: [UsersTable.id],
  }),
  lecture: one(LecturesTable, {
    fields: [SessionsTable.lectureId],
    references: [LecturesTable.id],
  }),
  zoomClient: one(ZoomClientsTable, {
    fields: [SessionsTable.zoomClientId],
    references: [ZoomClientsTable.id],
  }),
}));

// "Session" is overloaded in this codebase — auth's Redis-backed login
// session is `SessionPayload`/`SessionUser` (features/core/auth/types.ts).
// These two are always the class-meeting kind.
export type Session = typeof SessionsTable.$inferSelect;
export type NewSession = typeof SessionsTable.$inferInsert;
