import { relations } from "drizzle-orm";
import {
  foreignKey,
  index,
  integer,
  pgEnum,
  pgTable,
  timestamp,
  unique,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";
import { OrganizationsTable, UsersTable } from "@/drizzle/schemas/auth";
import { LecturesTable } from "@/drizzle/schemas/content";
import { createdAt, id, updatedAt } from "@/drizzle/schemas/helpers";
import { GroupsTable } from "./groups-table";

export const sessionStatusValues = [
  "scheduled",
  "ongoing",
  "completed",
  "cancelled",
] as const;
export type SessionStatus = (typeof sessionStatusValues)[number];
export const sessionStatusEnum = pgEnum("session_status", sessionStatusValues);

// One occurrence of a group's weekly schedule, generated by the
// `group/schedule-changed` Inngest function. Named `sessions`, not SOURCE's
// `zoom_sessions` (STATE.md D80): a class session is the domain concept and
// exists whether or not the deployment has Gateling Meetings configured — the
// meeting columns below stay null for a class nobody has started.
export const SessionsTable = pgTable(
  "sessions",
  {
    id,
    organizationId: uuid()
      .notNull()
      .references(() => OrganizationsTable.id, { onDelete: "cascade" }),
    groupId: uuid().notNull(),
    scheduledAt: timestamp({ withTimezone: true }).notNull(),
    durationMinutes: integer().notNull(),
    status: sessionStatusEnum().notNull().default("scheduled"),
    // All three are plain single-column FKs rather than the composite
    // (organizationId, x) shape used elsewhere: Postgres nulls *every* column
    // named in a composite FK's SET NULL action, including the NOT NULL
    // organizationId, so the delete throws instead of clearing the pointer
    // (STATE.md D79). Callers must therefore verify these belong to
    // ctx.organizationId before writing.
    teacherId: uuid().references(() => UsersTable.id, { onDelete: "set null" }),
    lectureId: uuid().references(() => LecturesTable.id, {
      onDelete: "set null",
    }),
    // The Gateling Meetings room this class runs in, created on demand when a
    // host presses "Start class" rather than ahead of schedule (STATE.md D143)
    // — so null means "not started yet", which is normal, and every read path
    // treats these as optional. `meetingCode` is Meetings' `abc-defg-hij`
    // handle; `joinUrl` is its plain share link (`guestUrl`), safe to hand to
    // anyone on the roster. There is deliberately no host-link column: host
    // links are single-use and minted per click (sessions/server/meetings.ts).
    meetingCode: varchar({ length: 64 }),
    joinUrl: varchar({ length: 1024 }),
    // Whose account holds host rights on Meetings' side — the assigned teacher
    // at the moment the class was started, or the admin who started an
    // unassigned one. Meetings binds host rights to this identity, so it is
    // recorded rather than re-derived: reassigning the teacher afterwards
    // must not silently demote the person who is actually running the room.
    meetingHostUserId: uuid().references(() => UsersTable.id, {
      onDelete: "set null",
    }),
    createdAt,
    updatedAt,
  },
  (table) => [
    index("sessions_organization_id_idx").on(table.organizationId),
    index("sessions_group_id_idx").on(table.groupId),
    index("sessions_scheduled_at_idx").on(table.scheduledAt),
    index("sessions_status_idx").on(table.status),
    // Makes regeneration idempotent — re-running the generator for an
    // unchanged schedule can be an onConflictDoNothing insert instead of a
    // delete-and-recreate that would churn ids on every save.
    unique("sessions_group_id_scheduled_at_unique").on(
      table.groupId,
      table.scheduledAt,
    ),
    // Phase 6's session_students hangs a composite FK off this pair.
    unique("sessions_organization_id_id_unique").on(
      table.organizationId,
      table.id,
    ),
    foreignKey({
      name: "sessions_organization_group_fk",
      columns: [table.organizationId, table.groupId],
      foreignColumns: [GroupsTable.organizationId, GroupsTable.id],
    }).onDelete("cascade"),
    // The webhook that closes a class looks its session up by the code
    // Meetings hands back (integrations/inngest/functions/on-meetings-webhook).
    index("sessions_meeting_code_idx").on(table.meetingCode),
  ],
);

export const sessionsRelations = relations(SessionsTable, ({ one }) => ({
  organization: one(OrganizationsTable, {
    fields: [SessionsTable.organizationId],
    references: [OrganizationsTable.id],
  }),
  group: one(GroupsTable, {
    fields: [SessionsTable.groupId],
    references: [GroupsTable.id],
  }),
  teacher: one(UsersTable, {
    fields: [SessionsTable.teacherId],
    references: [UsersTable.id],
  }),
  lecture: one(LecturesTable, {
    fields: [SessionsTable.lectureId],
    references: [LecturesTable.id],
  }),
  meetingHost: one(UsersTable, {
    fields: [SessionsTable.meetingHostUserId],
    references: [UsersTable.id],
  }),
}));

// "Session" is overloaded in this codebase — auth's Redis-backed login
// session is `SessionPayload`/`SessionUser` (features/core/auth/types.ts).
// These two are always the class-meeting kind.
export type Session = typeof SessionsTable.$inferSelect;
export type NewSession = typeof SessionsTable.$inferInsert;
